const emojis = [
  { value: '❤️', label: 'love' },
  { value: '👍', label: 'like' },
  { value: '🔥', label: 'fire' },
  { value: '😂', label: 'laugh' },
  { value: '🤔', label: 'thinking' },
  { value: '👀', label: 'eyes' },
  { value: '😮', label: 'wow' },
  { value: '😢', label: 'sad' },
  { value: '🤡', label: 'clown' },
  { value: '🙏', label: 'thanks' },
  { value: '💯', label: '100' },
  { value: '🌚', label: 'moon' },
  { value: '🤮', label: 'vomit' },
  { value: '💩', label: 'poop' },
  { value: '🚀', label: 'rocket' },
  { value: '✅', label: 'done' },
  { value: '⚡', label: 'zap' },
  { value: '🤯', label: 'mindblown' },
  { value: '👏', label: 'clap' },
  { value: '🤝', label: 'handshake' },
  { value: '🎉', label: 'party' },
  { value: '😎', label: 'cool' },
  { value: '💅', label: 'slay' },
  { value: '💸', label: 'money' },
  { value: '🤨', label: 'sus' },
  { value: '😇', label: 'angel' },
  { value: '😈', label: 'devil' },
  { value: '🍺', label: 'beer' },
  { value: '☕', label: 'coffee' },
  { value: '💊', label: 'pill' },
  { value: '🍌', label: 'banana' },
  { value: '💎', label: 'gem' },
  { value: '👻', label: 'ghost' },
  { value: '👾', label: 'alien' },
  { value: '🦾', label: 'robot' },
  { value: '🫠', label: 'melting' },
  { value: '🫡', label: 'salute' },
  { value: '🖕', label: 'middle finger' },
  { value: '🗿', label: 'moai' },
  { value: '🧊', label: 'ice' },
];

export default emojis;
