export const SCROLL_CONFIG = {
  HIGHLIGHT_DURATION_MS: 2000,
  JUMP_RESET_DELAY_MS: 400,
  TOP_SENTINEL_ROOT_MARGIN: '300px',
  BOTTOM_SENTINEL_ROOT_MARGIN: '0px',
  INTERSECTION_THRESHOLD: 0.1,
} as const;
